version: '3.9'
services:
  hammer:
    container_name: Hammer
    pull_policy: build
    build: https://github.com/BrackeysBot/Hammer.git#main
    volumes:
      - type: bind
        source: ./logs
        target: /app/logs
      - type: bind
        source: ./data
        target: /app/data
    restart: always
    env_file:
      - .env
