version: '3.9'
services:
  hammer:
    container_name: Hammer
    pull_policy: build
    build: https://github.com/BrackeysBot/Hammer.git#main
    volumes:
      - type: bind
        source: /var/log/brackeysbot/hammer
        target: /app/logs
      - type: bind
        source: /etc/brackeysbot/hammer
        target: /app/data
    restart: always
