//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Hammer.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class AuditLogReasons {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AuditLogReasons() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Hammer.Resources.AuditLogReasons", typeof(AuditLogReasons).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Banned by {staffMember.Username}#{staffMember.Discriminator}: {reason}.
        /// </summary>
        internal static string BannedUser {
            get {
                return ResourceManager.GetString("BannedUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gagged by {staffMember.Username}#{staffMember.Discriminator}.
        /// </summary>
        internal static string GaggedUser {
            get {
                return ResourceManager.GetString("GaggedUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kicked by {staffMember.Username}#{staffMember.Discriminator}: {reason}.
        /// </summary>
        internal static string KickedUser {
            get {
                return ResourceManager.GetString("KickedUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Muted by {staffMember.Username}#{staffMember.Discriminator}: {reason}.
        /// </summary>
        internal static string MutedUser {
            get {
                return ResourceManager.GetString("MutedUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Temp-Banned by {staffMember.Username}#{staffMember.Discriminator} ({duration}): {reason}.
        /// </summary>
        internal static string TempBannedUser {
            get {
                return ResourceManager.GetString("TempBannedUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Temp-Muted by {staffMember.Username}#{staffMember.Discriminator} ({duration}): {reason}.
        /// </summary>
        internal static string TempMutedUser {
            get {
                return ResourceManager.GetString("TempMutedUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Temporary ban expired..
        /// </summary>
        internal static string TemporaryBanExpired {
            get {
                return ResourceManager.GetString("TemporaryBanExpired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Temporary mute expired..
        /// </summary>
        internal static string TemporaryMuteExpired {
            get {
                return ResourceManager.GetString("TemporaryMuteExpired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unbanned by {staffMember.Username}#{staffMember.Discriminator}: {reason}.
        /// </summary>
        internal static string UnbannedUser {
            get {
                return ResourceManager.GetString("UnbannedUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unmuted by {staffMember.Username}#{staffMember.Discriminator}: {reason}.
        /// </summary>
        internal static string UnmutedUser {
            get {
                return ResourceManager.GetString("UnmutedUser", resourceCulture);
            }
        }
    }
}
