//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Hammer.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class EmbedFieldNames {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal EmbedFieldNames() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Hammer.Resources.EmbedFieldNames", typeof(EmbedFieldNames).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to __Attachments__.
        /// </summary>
        internal static string Attachments {
            get {
                return ResourceManager.GetString("Attachments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to __Author__.
        /// </summary>
        internal static string Author {
            get {
                return ResourceManager.GetString("Author", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to __Channel__.
        /// </summary>
        internal static string Channel {
            get {
                return ResourceManager.GetString("Channel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to __Content__.
        /// </summary>
        internal static string Content {
            get {
                return ResourceManager.GetString("Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to __Creation Time__.
        /// </summary>
        internal static string CreationTime {
            get {
                return ResourceManager.GetString("CreationTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to __Duration__.
        /// </summary>
        internal static string Duration {
            get {
                return ResourceManager.GetString("Duration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to __Expiration Time__.
        /// </summary>
        internal static string ExpirationTime {
            get {
                return ResourceManager.GetString("ExpirationTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to __Infraction ID__.
        /// </summary>
        internal static string InfractionID {
            get {
                return ResourceManager.GetString("InfractionID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to __Message__.
        /// </summary>
        internal static string Message {
            get {
                return ResourceManager.GetString("Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to __Message ID__.
        /// </summary>
        internal static string MessageID {
            get {
                return ResourceManager.GetString("MessageID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to __Message Time__.
        /// </summary>
        internal static string MessageTime {
            get {
                return ResourceManager.GetString("MessageTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to __Note ID__.
        /// </summary>
        internal static string NoteID {
            get {
                return ResourceManager.GetString("NoteID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to __Note Type__.
        /// </summary>
        internal static string NoteType {
            get {
                return ResourceManager.GetString("NoteType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to __Reason__.
        /// </summary>
        internal static string Reason {
            get {
                return ResourceManager.GetString("Reason", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to __Reporter__.
        /// </summary>
        internal static string Reporter {
            get {
                return ResourceManager.GetString("Reporter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to __Rule Broken__.
        /// </summary>
        internal static string RuleBroken {
            get {
                return ResourceManager.GetString("RuleBroken", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to __Staff Member__.
        /// </summary>
        internal static string StaffMember {
            get {
                return ResourceManager.GetString("StaffMember", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to __Total Infractions__.
        /// </summary>
        internal static string TotalInfractions {
            get {
                return ResourceManager.GetString("TotalInfractions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to __Total User Infractions__.
        /// </summary>
        internal static string TotalUserInfractions {
            get {
                return ResourceManager.GetString("TotalUserInfractions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to __User__.
        /// </summary>
        internal static string User {
            get {
                return ResourceManager.GetString("User", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to __User ID__.
        /// </summary>
        internal static string UserID {
            get {
                return ResourceManager.GetString("UserID", resourceCulture);
            }
        }
    }
}
