//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Hammer.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class EmbedMessages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal EmbedMessages() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Hammer.Resources.EmbedMessages", typeof(EmbedMessages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {user.Mention}, you have been **indefinitely banned** from **{guild.Name}**..
        /// </summary>
        internal static string BanDescription {
            get {
                return ResourceManager.GetString("BanDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to If you wish to discuss this with staff or feel this action is unjustified, please DM ModMail instead of posting about it in a public channel..
        /// </summary>
        internal static string DmModMail {
            get {
                return ResourceManager.GetString("DmModMail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {user.Mention}, you have been **kicked** from **{guild.Name}**. __This is not a permanent removal from the server__, but a way for staff to inform you that your behaviour needs to change if you wish to remain a member of the community in future.
        ///
        ///Please take some time to reflect on the reason for this action, and return when you feel you are ready..
        /// </summary>
        internal static string KickDescription {
            get {
                return ResourceManager.GetString("KickDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A message in {channel.Mention} was deleted by a staff member..
        /// </summary>
        internal static string MessageDeleted {
            get {
                return ResourceManager.GetString("MessageDeleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {user.Mention}, your message was deleted from {channel.Mention} as it was deemed either off-topic or violated our server rules..
        /// </summary>
        internal static string MessageDeletionDescription {
            get {
                return ResourceManager.GetString("MessageDeletionDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {user.Mention}, you have received a message from **{guild.Name}**. __This is not an infraction__..
        /// </summary>
        internal static string MessageFromStaff {
            get {
                return ResourceManager.GetString("MessageFromStaff", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {user.Mention} reported a message in {channel.Mention}..
        /// </summary>
        internal static string MessageReported {
            get {
                return ResourceManager.GetString("MessageReported", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {user.Mention}, thank you for your report.
        ///
        ///The following message has been brought to the attention of staff. If the message is deemed to violate server rules, appropriate action will be taken.
        ///__No further action is required on your part.__
        ///If you&apos;d like to discuss this report with staff, please DM ModMail instead of posting about it in a public channel..
        /// </summary>
        internal static string MessageReportFeedback {
            get {
                return ResourceManager.GetString("MessageReportFeedback", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {user.Mention}, you have been **indefinitely muted** from **{guild.Name}**..
        /// </summary>
        internal static string MuteDescription {
            get {
                return ResourceManager.GetString("MuteDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No note with the ID {id} could be found..
        /// </summary>
        internal static string NoSuchNote {
            get {
                return ResourceManager.GetString("NoSuchNote", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No user with the ID {id} could be found..
        /// </summary>
        internal static string NoSuchUser {
            get {
                return ResourceManager.GetString("NoSuchUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User {user.Id} ({user.Mention}) was found, but is not in this guild..
        /// </summary>
        internal static string NotInGuild {
            get {
                return ResourceManager.GetString("NotInGuild", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Staff member {staffMember.Mention} sent a message to {user.Mention}..
        /// </summary>
        internal static string StaffSentMessage {
            get {
                return ResourceManager.GetString("StaffSentMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {user.Mention}, you have been **temporarily banned** from **{guild.Name}**..
        /// </summary>
        internal static string TemporaryBanDescription {
            get {
                return ResourceManager.GetString("TemporaryBanDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {user.Mention}, you have been **temporarily muted** from **{guild.Name}**. A temporary mute is a way for staff to let you cool off and reflect on your behaviour.
        ///Failing to follow the rules in future will result in further infractions. Accumulating too many infractions may lead to an indefinite removal from the server..
        /// </summary>
        internal static string TemporaryMuteDescription {
            get {
                return ResourceManager.GetString("TemporaryMuteDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tracking disabled for {user.Mention}..
        /// </summary>
        internal static string TrackingDisabled {
            get {
                return ResourceManager.GetString("TrackingDisabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tracking enabled for {user.Mention}..
        /// </summary>
        internal static string TrackingEnabled {
            get {
                return ResourceManager.GetString("TrackingEnabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {user.Mention} is already blocked from reporting messages..
        /// </summary>
        internal static string UserAlreadyBlocked {
            get {
                return ResourceManager.GetString("UserAlreadyBlocked", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {user.Mention} will no longer be able to make message reports..
        /// </summary>
        internal static string UserBlocked {
            get {
                return ResourceManager.GetString("UserBlocked", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {user.Mention} was not previously blocked from reporting messages..
        /// </summary>
        internal static string UserNotBlocked {
            get {
                return ResourceManager.GetString("UserNotBlocked", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {user.Mention} has been unblocked. Their message reports will now be acknowledged..
        /// </summary>
        internal static string UserUnblocked {
            get {
                return ResourceManager.GetString("UserUnblocked", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {user.Mention}, you have received a **warning** from **{guild.Name}**. A warning is a way for staff to inform you that your behaviour needs to change, or further infractions will follow.
        ///Accumulating too many infractions may lead to an indefinite removal from the server..
        /// </summary>
        internal static string WarningDescription {
            get {
                return ResourceManager.GetString("WarningDescription", resourceCulture);
            }
        }
    }
}
