//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Hammer.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class EmbedTitles {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal EmbedTitles() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Hammer.Resources.EmbedTitles", typeof(EmbedTitles).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Message.
        /// </summary>
        internal static string Message {
            get {
                return ResourceManager.GetString("Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Message Deleted.
        /// </summary>
        internal static string MessageDeleted {
            get {
                return ResourceManager.GetString("MessageDeleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Message Reported.
        /// </summary>
        internal static string MessageReported {
            get {
                return ResourceManager.GetString("MessageReported", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Message Sent.
        /// </summary>
        internal static string MessageSent {
            get {
                return ResourceManager.GetString("MessageSent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No Such Note.
        /// </summary>
        internal static string NoSuchNote {
            get {
                return ResourceManager.GetString("NoSuchNote", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No Such User.
        /// </summary>
        internal static string NoSuchUser {
            get {
                return ResourceManager.GetString("NoSuchUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not In Guild.
        /// </summary>
        internal static string NotInGuild {
            get {
                return ResourceManager.GetString("NotInGuild", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tracking Disabled.
        /// </summary>
        internal static string TrackingDisabled {
            get {
                return ResourceManager.GetString("TrackingDisabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tracking Enabled.
        /// </summary>
        internal static string TrackingEnabled {
            get {
                return ResourceManager.GetString("TrackingEnabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Already Blocked.
        /// </summary>
        internal static string UserAlreadyBlocked {
            get {
                return ResourceManager.GetString("UserAlreadyBlocked", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reports Blocked.
        /// </summary>
        internal static string UserBlocked {
            get {
                return ResourceManager.GetString("UserBlocked", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not Blocked.
        /// </summary>
        internal static string UserNotBlocked {
            get {
                return ResourceManager.GetString("UserNotBlocked", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unblocked.
        /// </summary>
        internal static string UserUnblocked {
            get {
                return ResourceManager.GetString("UserUnblocked", resourceCulture);
            }
        }
    }
}
