//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Hammer.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class LoggerMessages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal LoggerMessages() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Hammer.Resources.LoggerMessages", typeof(LoggerMessages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Log channel {channel} was found for {guild}.
        /// </summary>
        internal static string LogChannelFound {
            get {
                return ResourceManager.GetString("LogChannelFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No log channel defined for {guild}. Actions for this guild will NOT be logged in Discord!.
        /// </summary>
        internal static string LogChannelNotDefined {
            get {
                return ResourceManager.GetString("LogChannelNotDefined", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Log channel for {guild} was not found. Actions for this guild will NOT be logged in Discord!.
        /// </summary>
        internal static string LogChannelNotFound {
            get {
                return ResourceManager.GetString("LogChannelNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {staffMember} sent a message to {recipient} from {guild}. Contents: {message}.
        /// </summary>
        internal static string StaffMessagedMember {
            get {
                return ResourceManager.GetString("StaffMessagedMember", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tracking disabled for {user} in {guild}.
        /// </summary>
        internal static string TrackingDisabledForUser {
            get {
                return ResourceManager.GetString("TrackingDisabledForUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tracking enabled for {user} in {guild}.
        /// </summary>
        internal static string TrackingEnabledForUser {
            get {
                return ResourceManager.GetString("TrackingEnabledForUser", resourceCulture);
            }
        }
    }
}
